tidb:
  host: advanced-tidb-tidb.tidb-cluster
  port: 4000
  database: yifu_produce
  username: root
  password: Mesgxgk@12345
minio:
  url: http://172.25.11.142:9000
  bucket: test_kubernetes_tidb_data
  csvName: data